services:
  etl:
    build: ./etl
    volumes:
      - ./etl:/app
      - ./data:/app/data
    command: sleep infinity

  api:
    build: ./api
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app
      - ./data:/app/data:ro
      - .:/workspaces:cached
    command: sleep infinity
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - .:/workspaces:cached
    depends_on:
      - api
    environment:
      - NEXT_PUBLIC_API_URL=http://api:8080
    command: sleep infinity