services:
  etl:
    build: ./etl
    volumes:
      - ./etl:/app
      - ./data:/app/data
    command: sleep infinity

  api:
    build: ./api
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app
      - ./data:/app/data:ro
      - .:/workspaces:cached
    command: sleep infinity